config/routes.rb
Avatari::Application.routes.draw do
  resources :transactions

  resources :accounts

  get "session/login"
  post "session/auth"
  
  resources :avatars

  get "dashboard/index"
  get "dashboard/initialize_avatar"
  post "dashboard/set_avatar"

  post "lti/connect"

  get "lti/dashboard"

  get "lti/tool_config"
  match 'shop(/index)' => 'shop#index'
  get "shop/chest"
  post "shop/open_chest"
  resources :owned_items
  post "owned_items/sellback"
  
  resources :individuals

  resources :target_areas

  resources :items
  root :to => 'items#new'

end

app/models/individual.rb
class Individual < ActiveRecord::Base
  attr_accessible :canvas_id, :email, :firstname, :gradyear, :lastname, :sisid, :type, :avatar_id
  belongs_to :avatar
  has_one :account
  has_many :owned_items
  has_many :items, :through => :owned_items
  has_many :worn_items, :class_name => OwnedItem, :conditions => 'owned_items.wearing = 1'
  
  def fullname
    self.firstname + " " + self.lastname
  end
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  # GET /individuals
  # GET /individuals.json
  def index
    @individuals = Individual.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @individuals }
    end
  end

  # GET /individuals/1
  # GET /individuals/1.json
  def show
    @current_user = current_user
    @individual = Individual.find(params[:id])
    unless @individual.account
      @account = @individual.create_account
    else
      @account = @individual.account
    end
      
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @individual }
    end
  end

  # GET /individuals/new
  # GET /individuals/new.json
  def new
    @individual = Individual.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @individual }
    end
  end

  # GET /individuals/1/edit
  def edit
    @individual = Individual.find(params[:id])
  end

  # POST /individuals
  # POST /individuals.json
  def create
    @individual = Individual.new(params[:individual])

    respond_to do |format|
      if @individual.save
        format.html { redirect_to @individual, notice: 'Individual was successfully created.' }
        format.json { render json: @individual, status: :created, location: @individual }
      else
        format.html { render action: "new" }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /individuals/1
  # PUT /individuals/1.json
  def update
    @individual = Individual.find(params[:id])

    respond_to do |format|
      if @individual.update_attributes(params[:individual])
        format.html { redirect_to @individual, notice: 'Individual was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individuals/1
  # DELETE /individuals/1.json
  def destroy
    @individual = Individual.find(params[:id])
    @individual.destroy

    respond_to do |format|
      format.html { redirect_to individuals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/individuals/_fashion_description.html.erb
<div id='fashion_description'>
<h2><%=@individual.firstname%> is wearing...</h2>
<%@individual.owned_items.where("wearing = 1").each do |witem| %>
  <p><strong><%=witem.item.name%>:</strong><%=witem.item.description%></p>
<%end%>
</div>

app/views/individuals/_form.html.erb
<%= form_for(@individual) do |f| %>
  <% if @individual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

      <ul>
      <% @individual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :avatar_id %><br />
    <%= f.select :avatar_id, Avatar.all.collect {|avatar| [avatar.name,avatar.id]} %>
  </div>
  <div class="field">
    <%= f.label :canvas_id %><br />
    <%= f.number_field :canvas_id %>
  </div>
  <div class="field">
    <%= f.label :sisid %><br />
    <%= f.text_field :sisid %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :gradyear %><br />
    <%= f.number_field :gradyear %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/individuals/_stats.html.erb
<div id='stats'>
  <h2>Account Balance: <%= number_to_currency(@individual.account.balance) %></h2>
  <h3>Wardrobe Size: <%= @individual.owned_items.size %></h3>
  <h3>Wardrobe Value: <%= number_to_currency(@individual.owned_items.collect {|oitem| oitem.item.value.to_f}.sum) %></h3>
</div>

app/views/individuals/_svg_avatar.html.erb
<% avatari_svg do %>
  <%= render @individual.avatar if @individual.avatar %>
  <%= " " %>
  <% @individual.worn_items.each do |witem| %>
    <%= render witem %>
  <% end %>
  
<% end %>

<script>
  <%@individual.worn_items.each do |worn_item|%>
    <% if worn_item.color? %>
      <%color_code, action, color = worn_item.color.split(":")%>
      d3.selectAll("#g_owned_item_<%=worn_item.id%> path.<%=color_code%>").transition().duration(2000).style("<%=action%>", "<%=color%>");
    <%end%>
  <%end%>
</script>

app/views/individuals/edit.html.erb
<h1>Editing individual</h1>

<%= render 'form' %>

<%= link_to 'Show', @individual %> |
<%= link_to 'Back', individuals_path %>

app/views/individuals/index.html.erb
<h1>Listing individuals</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Canvas</th>
    <th>Sisid</th>
    <th>Email</th>
    <th>Type</th>
    <th>Gradyear</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @individuals.each do |individual| %>
  <tr>
    <td><%= individual.firstname %></td>
    <td><%= individual.lastname %></td>
    <td><%= individual.canvas_id %></td>
    <td><%= individual.sisid %></td>
    <td><%= individual.email %></td>
    <td><%= individual.type %></td>
    <td><%= individual.gradyear %></td>
    <td><%= link_to 'Show', individual %></td>
    <td><%= link_to 'Edit', edit_individual_path(individual) %></td>
    <td><%= link_to 'Destroy', individual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Individual', new_individual_path %>

app/views/individuals/new.html.erb
<h1>New individual</h1>

<%= render 'form' %>

<%= link_to 'Back', individuals_path %>

app/views/individuals/show.html.erb
<h1>Wardrobe - <%= @individual.firstname + " " + @individual.lastname %></h1>

<%= render :partial => "svg_avatar", :individual => @individual %>
<%= render :partial => "stats"%>
<% link_to 'Edit', edit_individual_path(@individual) %>
<% link_to 'Back', individuals_path %>
<h3>Wardrobe</h3>
<div id='wardrobe'>
<% @individual.owned_items.joins(:item).order("target_area_id").each do |owned_item| %>
  <%= link_to(edit_owned_item_path(owned_item)) do %>
    <% avatari_svg(:class => owned_item.wearing ? 'wearing' : '') do %>
      <%= render owned_item %>
    <% end %>
  <% end %>
<% end %>
</div>
<script>
  <%@individual.owned_items.each do |worn_item|%>
    <% if worn_item.color? %>
      <%color_code, action, color = worn_item.color.split(":")%>
      d3.selectAll("#g_owned_item_<%=worn_item.id%> path.<%=color_code%>").transition().duration(2000).style("<%=action%>", "<%=color%>");
    <%end%>
  <%end%>
</script>